Add extra parentheses to help g++ parsing. It appears to be confused by the function call: core::XYZ(all[i]) (i.e. "call the XYZ constructor, passing all[i] as an argument") and instead parsing it as: core::XYZ all[i] (i.e. "declare an array called "all" of length i of defaultly-constructed XYZ objects") even though it should know better because "all" already exists as a variable in this scope.
This results in the following error when compiled with gcc (Ubuntu 4.4.3-4ubuntu5) 4.4.3:
modules/display/src/restraint_geometry.cpp:91: error: parameter may
not have variably modified type 'IMP::core::XYZ [(((long unsigned
int)(((long int)i) + -0x00000000000000001)) + 1)]'

This patch fixes the problem, for Frido at least.

gcc developers seem divided on whether this is a feature or a bug.


git-svn-id: https://svn.salilab.org/imp/trunk@7462 e91f8c7b-0e32-4433-a9ac-4502d39a4eab