Skip debug source packages in RPM Fedora 27 build.
Fedora 27 turns on the building of debugsource RPM
packages by default, but this causes the build to fail
with
error: Empty %files file [...]/debugsourcefiles.list
Work around this for now by simply disabling the building
of debugsource packages.